/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_SHAREDIR "c:/Program Files/Qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_WIN32 1
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define CONFIG_AUDIO_DRIVERS \
    &winwave_audio_driver,\

#define CONFIG_WINWAVE 1
#define CONFIG_AUDIO_WIN_INT 1
#define CONFIG_BDRV_WHITELIST \
    NULL
#define QEMU_VERSION "0.12.3"
#define QEMU_PKGVERSION ""
#define CONFIG_UNAME_RELEASE ""
#define CONFIG_ZERO_MALLOC 1
